apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ cookiecutter.project_slug.lower()|replace(' ', '-')|replace('_', '-')|replace('.', '-')|trim() }}
  namespace: {{cookiecutter.project_namespace}}
  annotations: {}
  labels:
    app: {{ cookiecutter.project_slug.lower()|replace(' ', '-')|replace('_', '-')|replace('.', '-')|trim() }}
spec:
  rules:
    - host: ${INGRESS_HOST}
      http:
        paths:
        - backend:
            serviceName: {{ cookiecutter.project_slug.lower()|replace(' ', '-')|replace('_', '-')|replace('.', '-')|trim() }}-external
            servicePort: 80
          path: /
        - backend:
            serviceName: {{ cookiecutter.project_slug.lower()|replace(' ', '-')|replace('_', '-')|replace('.', '-')|trim() }}
            servicePort: 9095
          path: /metrics
