apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ cookiecutter.project_slug.lower()|replace(' ', '-')|replace('_', '-')|replace('.', '-')|trim() }}
  name: {{ cookiecutter.project_slug.lower()|replace(' ', '-')|replace('_', '-')|replace('.', '-')|trim() }}
  namespace: {{cookiecutter.project_namespace}}
