bases:
  - ../../base
namespace: {{cookiecutter.project_namespace}}
resources:
  - network_policy.yml

patchesStrategicMerge:
  - config.yml

patchesJson6902:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: {{ cookiecutter.project_slug.lower()|replace(' ', '-')|replace('_', '-')|replace('.', '-')|trim() }}
    path: ingress_patch.yml

  - target:
      group: apps
      version: v1
      kind: Deployment
      name: {{ cookiecutter.project_slug.lower()|replace(' ', '-')|replace('_', '-')|replace('.', '-')|trim() }}
    path: deployment_patch.yml
