from werkzeug.middleware.proxy_fix import ProxyFix

from {{cookiecutter.project_slug}} import config
from {{cookiecutter.project_slug}}.models import db


# This hook ensures that a connection is opened to handle any queries
# generated by the request.
def _db_connect():
    db.connect(reuse_if_open=True)


# This hook ensures that the connection is closed when we've finished
# processing the request.
def _db_close(exc):  # noqa W0613
    if not db.is_closed():
        db.close()


def init_app(app):
    app.before_request(_db_connect)
    app.teardown_request(_db_close)

    app.wsgi_app = ProxyFix(
        app.wsgi_app,
        x_for=config.TRUSTED_PROXIES_NUMBER,
        x_host=1,
    )
